/**
 * Auto-generated TypeScript types mirroring packages/gateway/crabcode_gateway/schemas.py
 *
 * ─── HOW TO REGENERATE ────────────────────────────────────────────
 *   python packages/vscode/scripts/gen-types.py
 *
 * Do NOT edit this file by hand unless you also update the generator.
 * ──────────────────────────────────────────────────────────────────
 */

// ── Request types ────────────────────────────────────────────────────
export interface SendMessageRequest {
  text: string;
  max_turns?: number;
  session_id?: string | null;
}

export interface NewSessionRequest {
  cwd?: string | null;
}

export interface ResumeSessionRequest {
  session_id: string;
}

export interface CompactRequest {
  session_id: string;
}

export interface InterruptRequest {
  session_id: string;
}

export interface PermissionResponseRequest {
  tool_use_id: string;
  allowed: boolean;
  always_allow?: boolean;
  agent_id?: string | null;
}

export interface ChoiceResponseRequest {
  tool_use_id: string;
  selected: string[];
  cancelled?: boolean;
  agent_id?: string | null;
}

export interface SpawnAgentRequest {
  prompt: string;
  subagent_type?: string;
  name?: string | null;
  model_profile?: string | null;
}

export interface AgentInputRequest {
  prompt: string;
  interrupt?: boolean;
}

export interface WaitAgentRequest {
  agent_id: string | string[];
  timeout_ms?: number | null;
}

export interface SwitchModelRequest {
  name: string;
}

export interface SwitchModeRequest {
  mode: "agent" | "plan";
}

/**
 * Client pushes workspace context to the server.
 * 
 * Used by VSCode extension to inform the gateway about the current
 * editor state (active file, selection, cursor position, etc.).
 */
export interface ContextPushRequest {
  session_id: string;
  active_file?: string | null;
  selected_text?: string | null;
  cursor_line?: number | null;
  cursor_column?: number | null;
  open_files?: string[];
  language_id?: string | null;
}

/** Create a checkpoint with file snapshot. */
export interface CheckpointRequest {
  session_id: string;
  label?: string;
}

/** Revert files + conversation to a checkpoint. */
export interface RevertRequest {
  session_id: string;
  checkpoint_id: string;
}


// ── Response / info types ────────────────────────────────────────────
export interface SessionInfo {
  session_id: string;
  message_count?: number;
  model?: string;
  provider?: string;
  created_at?: string;
}

export interface AgentInfo {
  agent_id: string;
  title: string;
  subagent_type: string;
  status: string;
  model: string;
  created_at: string;
  parent_agent_id?: string | null;
  usage?: Record<string, unknown>;
  final_result?: string;
  error?: string;
}

export interface ToolInfo {
  name: string;
  description?: string;
  is_read_only?: boolean;
  is_enabled?: boolean;
}

export interface ModelInfo {
  name: string;
  description?: string;
}

export interface HealthResponse {
  status?: string;
  version?: string;
}


// ── EventPayload tagged union ────────────────────────────────────────
export interface StreamTextPayload {
  text: string;
  type?: "stream_text";
}

export interface ThinkingPayload {
  text: string;
  type?: "thinking";
}

export interface ToolUsePayload {
  tool_name: string;
  tool_input: Record<string, unknown>;
  tool_use_id: string;
  type?: "tool_use";
  agent_id?: string | null;
}

export interface ToolResultPayload {
  tool_use_id: string;
  tool_name: string;
  result: string;
  type?: "tool_result";
  is_error?: boolean;
  result_for_display?: string | null;
  agent_id?: string | null;
}

export interface PermissionRequestPayload {
  tool_name: string;
  tool_input: Record<string, unknown>;
  tool_use_id: string;
  type?: "permission_request";
  reason?: string | null;
  permission_key?: string | null;
  agent_id?: string | null;
}

export interface PermissionResponsePayload {
  tool_use_id: string;
  allowed: boolean;
  type?: "permission_response";
  always_allow?: boolean;
  agent_id?: string | null;
}

export interface ChoiceRequestPayload {
  tool_use_id: string;
  question: string;
  options: string[];
  type?: "choice_request";
  multiple?: boolean;
  agent_id?: string | null;
}

export interface ChoiceResponsePayload {
  tool_use_id: string;
  selected: string[];
  type?: "choice_response";
  cancelled?: boolean;
  agent_id?: string | null;
}

export interface CompactPayload {
  summary: string;
  type?: "compact";
  messages_before?: number;
  messages_after?: number;
}

export interface ErrorPayload {
  message: string;
  type?: "error";
  recoverable?: boolean;
  error_type?: string;
}

export interface TurnCompletePayload {
  type?: "turn_complete";
  reason?: string;
  turn_count?: number;
  usage?: Record<string, unknown>;
}

export interface StreamModePayload {
  mode: string;
  type?: "stream_mode";
  agent_id?: string | null;
}

export interface AgentStatePayload {
  agent_id: string;
  status: string;
  subagent_type: string;
  title: string;
  type?: "agent_state";
  parent_agent_id?: string | null;
  message?: string;
  usage?: Record<string, unknown>;
}

export interface AgentOutputPayload {
  agent_id: string;
  stream: string;
  text: string;
  type?: "agent_output";
  tool_name?: string | null;
}

export interface ModeChangePayload {
  mode: string;
  type?: "mode_change";
  reason?: string;
}

export interface PlanReadyPayload {
  plan: Record<string, unknown>;
  type?: "plan_ready";
}

export interface TeamMessagePayload {
  team_id: string;
  from_agent: string;
  to_agent: string;
  text: string;
  type?: "team_message";
  msg_type?: string;
  message_id?: string;
}

export interface TeamStatePayload {
  team_id: string;
  agent_id: string;
  old_state: string;
  new_state: string;
  type?: "team_state";
  role?: string;
}

export interface TaskUpdatePayload {
  team_id: string;
  task_id: string;
  status: string;
  type?: "task_update";
  assignee?: string | null;
  description?: string;
}

/**
 * File change notification for frontends (VSCode, etc.).
 * 
 * Emitted when a tool modifies the filesystem so the client can
 * refresh its editor view, show diffs, etc.
 */
export interface FileChangePayload {
  path: string;
  action: "create" | "modify" | "delete";
  type?: "file_change";
  diff?: string | null;
}

export interface SnapshotPayload {
  snapshot_id: string;
  tool_name: string;
  type?: "snapshot";
  files?: string[];
}

export interface RevertPayload {
  snapshot_id: string;
  type?: "revert";
  files_restored?: string[];
}

export interface ServerConnectedPayload {
  type?: "server.connected";
  properties?: Record<string, unknown>;
}

export interface ServerHeartbeatPayload {
  type?: "server.heartbeat";
  properties?: Record<string, unknown>;
}


// ── Tagged union ─────────────────────────────────────────────────────
export type EventPayload =
  | StreamTextPayload |
  ThinkingPayload |
  ToolUsePayload |
  ToolResultPayload |
  PermissionRequestPayload |
  PermissionResponsePayload |
  ChoiceRequestPayload |
  ChoiceResponsePayload |
  CompactPayload |
  ErrorPayload |
  TurnCompletePayload |
  StreamModePayload |
  AgentStatePayload |
  AgentOutputPayload |
  ModeChangePayload |
  PlanReadyPayload |
  TeamMessagePayload |
  TeamStatePayload |
  TaskUpdatePayload |
  FileChangePayload |
  SnapshotPayload |
  RevertPayload |
  ServerConnectedPayload |
  ServerHeartbeatPayload;

// ── Type discriminator helper ────────────────────────────────────────
export type EventPayloadType = EventPayload["type"];

