# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import crabcode_pb2 as crabcode__pb2


class CrabCodeServiceStub(object):
    """── Service ─────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_stream(
                '/crabcode.CrabCodeService/SendMessage',
                request_serializer=crabcode__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=crabcode__pb2.CoreEventProto.FromString,
                )
        self.SubscribeEvents = channel.unary_stream(
                '/crabcode.CrabCodeService/SubscribeEvents',
                request_serializer=crabcode__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=crabcode__pb2.CoreEventProto.FromString,
                )
        self.SpawnAgent = channel.unary_unary(
                '/crabcode.CrabCodeService/SpawnAgent',
                request_serializer=crabcode__pb2.SpawnAgentRequest.SerializeToString,
                response_deserializer=crabcode__pb2.SpawnAgentResponse.FromString,
                )
        self.GetAgent = channel.unary_unary(
                '/crabcode.CrabCodeService/GetAgent',
                request_serializer=crabcode__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=crabcode__pb2.AgentSnapshotProto.FromString,
                )
        self.ListAgents = channel.unary_unary(
                '/crabcode.CrabCodeService/ListAgents',
                request_serializer=crabcode__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=crabcode__pb2.ListAgentsResponse.FromString,
                )
        self.CancelAgent = channel.unary_unary(
                '/crabcode.CrabCodeService/CancelAgent',
                request_serializer=crabcode__pb2.CancelAgentRequest.SerializeToString,
                response_deserializer=crabcode__pb2.CancelAgentResponse.FromString,
                )
        self.WaitAgent = channel.unary_unary(
                '/crabcode.CrabCodeService/WaitAgent',
                request_serializer=crabcode__pb2.WaitAgentRequest.SerializeToString,
                response_deserializer=crabcode__pb2.AgentSnapshotProto.FromString,
                )
        self.RespondPermission = channel.unary_unary(
                '/crabcode.CrabCodeService/RespondPermission',
                request_serializer=crabcode__pb2.PermissionResponseMsg.SerializeToString,
                response_deserializer=crabcode__pb2.Empty.FromString,
                )
        self.RespondChoice = channel.unary_unary(
                '/crabcode.CrabCodeService/RespondChoice',
                request_serializer=crabcode__pb2.ChoiceResponseMsg.SerializeToString,
                response_deserializer=crabcode__pb2.Empty.FromString,
                )
        self.ListModels = channel.unary_unary(
                '/crabcode.CrabCodeService/ListModels',
                request_serializer=crabcode__pb2.Empty.SerializeToString,
                response_deserializer=crabcode__pb2.ListModelsResponse.FromString,
                )
        self.SwitchModel = channel.unary_unary(
                '/crabcode.CrabCodeService/SwitchModel',
                request_serializer=crabcode__pb2.SwitchModelRequest.SerializeToString,
                response_deserializer=crabcode__pb2.Empty.FromString,
                )
        self.SwitchMode = channel.unary_unary(
                '/crabcode.CrabCodeService/SwitchMode',
                request_serializer=crabcode__pb2.SwitchModeRequest.SerializeToString,
                response_deserializer=crabcode__pb2.Empty.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/crabcode.CrabCodeService/HealthCheck',
                request_serializer=crabcode__pb2.Empty.SerializeToString,
                response_deserializer=crabcode__pb2.HealthCheckResponse.FromString,
                )


class CrabCodeServiceServicer(object):
    """── Service ─────────────────────────────────────────────────────

    """

    def SendMessage(self, request, context):
        """Streaming conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Subscribe to all events for a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpawnAgent(self, request, context):
        """Agent management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondPermission(self, request, context):
        """Permission & choice
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondChoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrabCodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=crabcode__pb2.SendMessageRequest.FromString,
                    response_serializer=crabcode__pb2.CoreEventProto.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=crabcode__pb2.SubscribeRequest.FromString,
                    response_serializer=crabcode__pb2.CoreEventProto.SerializeToString,
            ),
            'SpawnAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnAgent,
                    request_deserializer=crabcode__pb2.SpawnAgentRequest.FromString,
                    response_serializer=crabcode__pb2.SpawnAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=crabcode__pb2.GetAgentRequest.FromString,
                    response_serializer=crabcode__pb2.AgentSnapshotProto.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=crabcode__pb2.ListAgentsRequest.FromString,
                    response_serializer=crabcode__pb2.ListAgentsResponse.SerializeToString,
            ),
            'CancelAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAgent,
                    request_deserializer=crabcode__pb2.CancelAgentRequest.FromString,
                    response_serializer=crabcode__pb2.CancelAgentResponse.SerializeToString,
            ),
            'WaitAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitAgent,
                    request_deserializer=crabcode__pb2.WaitAgentRequest.FromString,
                    response_serializer=crabcode__pb2.AgentSnapshotProto.SerializeToString,
            ),
            'RespondPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondPermission,
                    request_deserializer=crabcode__pb2.PermissionResponseMsg.FromString,
                    response_serializer=crabcode__pb2.Empty.SerializeToString,
            ),
            'RespondChoice': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondChoice,
                    request_deserializer=crabcode__pb2.ChoiceResponseMsg.FromString,
                    response_serializer=crabcode__pb2.Empty.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=crabcode__pb2.Empty.FromString,
                    response_serializer=crabcode__pb2.ListModelsResponse.SerializeToString,
            ),
            'SwitchModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchModel,
                    request_deserializer=crabcode__pb2.SwitchModelRequest.FromString,
                    response_serializer=crabcode__pb2.Empty.SerializeToString,
            ),
            'SwitchMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchMode,
                    request_deserializer=crabcode__pb2.SwitchModeRequest.FromString,
                    response_serializer=crabcode__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=crabcode__pb2.Empty.FromString,
                    response_serializer=crabcode__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crabcode.CrabCodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CrabCodeService(object):
    """── Service ─────────────────────────────────────────────────────

    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/crabcode.CrabCodeService/SendMessage',
            crabcode__pb2.SendMessageRequest.SerializeToString,
            crabcode__pb2.CoreEventProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/crabcode.CrabCodeService/SubscribeEvents',
            crabcode__pb2.SubscribeRequest.SerializeToString,
            crabcode__pb2.CoreEventProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SpawnAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/SpawnAgent',
            crabcode__pb2.SpawnAgentRequest.SerializeToString,
            crabcode__pb2.SpawnAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/GetAgent',
            crabcode__pb2.GetAgentRequest.SerializeToString,
            crabcode__pb2.AgentSnapshotProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/ListAgents',
            crabcode__pb2.ListAgentsRequest.SerializeToString,
            crabcode__pb2.ListAgentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/CancelAgent',
            crabcode__pb2.CancelAgentRequest.SerializeToString,
            crabcode__pb2.CancelAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WaitAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/WaitAgent',
            crabcode__pb2.WaitAgentRequest.SerializeToString,
            crabcode__pb2.AgentSnapshotProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RespondPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/RespondPermission',
            crabcode__pb2.PermissionResponseMsg.SerializeToString,
            crabcode__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RespondChoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/RespondChoice',
            crabcode__pb2.ChoiceResponseMsg.SerializeToString,
            crabcode__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/ListModels',
            crabcode__pb2.Empty.SerializeToString,
            crabcode__pb2.ListModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SwitchModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/SwitchModel',
            crabcode__pb2.SwitchModelRequest.SerializeToString,
            crabcode__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SwitchMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/SwitchMode',
            crabcode__pb2.SwitchModeRequest.SerializeToString,
            crabcode__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crabcode.CrabCodeService/HealthCheck',
            crabcode__pb2.Empty.SerializeToString,
            crabcode__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
